#!/usr/bin/env bash
# PreToolUse guard for ClearAF: protects credentials, the migration chain and hosted infrastructure.
# Exit 2 blocks the call (stderr is shown to Claude). A JSON "ask" decision forces a confirmation prompt.
set -uo pipefail
input=$(cat)
tool=$(jq -r '.tool_name // ""' <<<"$input")
root="${CLAUDE_PROJECT_DIR:-$(pwd)}"

deny() { echo "Blocked by .claude/hooks/guard.sh: $1" >&2; exit 2; }
ask() { jq -n --arg r "$1" '{hookSpecificOutput:{hookEventName:"PreToolUse",permissionDecision:"ask",permissionDecisionReason:$r}}'; exit 0; }

case "$tool" in
  Read|Edit|Write|MultiEdit|NotebookEdit)
    f=$(jq -r '.tool_input.file_path // .tool_input.notebook_path // ""' <<<"$input")
    rel="${f#"$root"/}"
    case "$rel" in
      *.env.example) ;;
      .env|*/.env|.env.*|*/.env.*) deny "dotenv files hold local or production credentials. Variable names are in .env.example." ;;
      .local/*|handoff-*/*) deny "$rel is private, access-restricted material (demo credentials, manifests, snapshots)." ;;
      ClearAF/Config/Local.generated.xcconfig) deny "generated by scripts/local.cjs; regenerate with 'node scripts/local.cjs configure'." ;;
    esac
    if [[ "$tool" != Read ]]; then
      case "$rel" in
        supabase/legacy-migrations/*) deny "archived Prisma chain; never edit or replay it." ;;
        supabase/baseline.json) deny "binds the reviewed baseline fingerprint; do not edit." ;;
        supabase/migrations/*)
          if git -C "$root" ls-files --error-unmatch "$rel" >/dev/null 2>&1; then
            deny "$rel is committed, so treat it as applied. Add a new migration: npx --yes supabase@2.117.0 migration new <name>"
          fi ;;
        package-lock.json|*/package-lock.json) deny "lockfiles change only through npm install/ci." ;;
      esac
    fi ;;
  Bash)
    cmd=$(jq -r '.tool_input.command // ""' <<<"$input")
    # Match only at a command position (line start or after ; & | ( ) so commit messages and PR text don't trip rules.
    # This is a guardrail against mistakes, not a sandbox.
    at='(^|[;&|(])[[:space:]]*(npx[[:space:]]+(--yes[[:space:]]+)?)?'
    has() { grep -qE "$at$1" <<<"$cmd"; }
    if has 'prisma[[:space:]]+(migrate|db[[:space:]]+push)'; then
      deny "Prisma migrations are retired; schema changes go through supabase/migrations (docs/baseline/README.md)."
    fi
    if has 'supabase(@[0-9.]+)?[[:space:]]+db[[:space:]]+reset' && grep -qE -- '--linked|--db-url' <<<"$cmd"; then
      deny "db reset against a hosted database is forbidden."
    fi
    if has 'vercel[[:space:]]+env[[:space:]]+pull'; then
      deny "never copy production environment settings into the local checkout."
    fi
    if has '(cat|less|more|head|tail|bat|source)[[:space:]][^;&|]*(\.env([[:space:]]|$|\.local|\.production)|\.local/|handoff-)'; then
      deny "don't print credential files or private material."
    fi
    if has 'supabase(@[0-9.]+)?[[:space:]]+db[[:space:]]+push'; then
      ask "Applies migrations to a database that may be hosted. Is there a recoverable backup, and has the SQL been reviewed?"
    fi
    if has 'vercel([[:space:]]+deploy)?[[:space:]]+[^;&|]*--prod' || has 'vercel[[:space:]]+(rollback|promote|env[[:space:]]+(add|rm))'; then
      ask "Production Vercel change. Has the rollback target been recorded with 'vercel inspect'?"
    fi
    ;;
esac
exit 0
