version: 2

# Ignore Supabase anon key (public key, safe to commit)
paths-ignore:
  - ClearAF/Config/SupabaseConfig.swift

# Only block service role keys
matches-ignore:
  - name: Supabase anon key
    match: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdscmZ4anlkZWJuaWxzcHRsa3NnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU1MzUyNTksImV4cCI6MjA3MTExMTI1OX0.CqVuJxORUU6PgL-o7ElT_0j9M2wmX65FOuvp8wP7K6E