// Extracts the ClearAF mark's "af" monogram as outline path data from the bundled font and writes it
// for both clients. Run from the repository root:
//   swift scripts/brand/extract-glyphs.swift          (writes)
//   swift scripts/brand/extract-glyphs.swift --check  (exits 1 if the committed files differ)
// Output is plain text with 4-decimal em coordinates, so it is byte-identical on every run.
import CoreGraphics
import CoreText
import Foundation

let italicFont = "ClearAF/Fonts/Newsreader16pt-LightItalic.ttf"
let romanFont = "ClearAF/Fonts/Newsreader16pt-Light.ttf"
let swiftOutput = "ClearAF/Views/Brand/LetterpressMarkGlyphs.swift"
let tsOutput = "web-portal/src/components/brand/mark-glyphs.ts"

func loadFont(_ path: String) -> CTFont {
    guard let data = FileManager.default.contents(atPath: path),
          let descriptor = CTFontManagerCreateFontDescriptorFromData(data as CFData) else {
        FileHandle.standardError.write("Cannot read \(path). Run from the repository root.\n".data(using: .utf8)!)
        exit(2)
    }
    let probe = CTFontCreateWithFontDescriptor(descriptor, 12, nil)
    // Size the font at its units-per-em so CoreText coordinates are font units.
    return CTFontCreateWithFontDescriptor(descriptor, CGFloat(CTFontGetUnitsPerEm(probe)), nil)
}

func number(_ value: CGFloat) -> String {
    var text = String(format: "%.4f", Double(value))
    while text.hasSuffix("0") { text.removeLast() }
    if text.hasSuffix(".") { text.removeLast() }
    return text == "-0" ? "0" : text
}

/// Advance width of `text` in em, kerning applied by CoreText.
func advanceEm(_ text: String, _ font: CTFont) -> CGFloat {
    let line = CTLineCreateWithAttributedString(NSAttributedString(string: text, attributes: [kCTFontAttributeName as NSAttributedString.Key: font]))
    return CGFloat(CTLineGetTypographicBounds(line, nil, nil, nil)) / CTFontGetSize(font)
}

let italic = loadFont(italicFont)
let roman = loadFont(romanFont)
let upm = CTFontGetSize(italic)
let line = CTLineCreateWithAttributedString(NSAttributedString(string: "af", attributes: [kCTFontAttributeName as NSAttributedString.Key: italic]))
let advanceEnd = CGFloat(CTLineGetTypographicBounds(line, nil, nil, nil))
let ascent = CTFontGetAscent(italic) / upm
let descent = CTFontGetDescent(italic) / upm
// A CSS line box at line-height 1 puts the baseline (1 + descent - ascent) / 2 em above its bottom edge.
let baselineAboveBottom = (1 + descent - ascent) / 2

var commands: [String] = []
for run in CTLineGetGlyphRuns(line) as! [CTRun] {
    let count = CTRunGetGlyphCount(run)
    var glyphs = [CGGlyph](repeating: 0, count: count)
    var positions = [CGPoint](repeating: .zero, count: count)
    CTRunGetGlyphs(run, CFRange(location: 0, length: 0), &glyphs)
    CTRunGetPositions(run, CFRange(location: 0, length: 0), &positions)
    for index in 0..<count {
        guard let outline = CTFontCreatePathForGlyph(italic, glyphs[index], nil) else { continue }
        let offset = positions[index].x
        // Em units, y down, origin at the bottom-right corner of the line box.
        func point(_ p: CGPoint) -> String {
            "\(number((p.x + offset - advanceEnd) / upm)) \(number(-p.y / upm - baselineAboveBottom))"
        }
        outline.applyWithBlock { element in
            let e = element.pointee
            switch e.type {
            case .moveToPoint: commands.append("M\(point(e.points[0]))")
            case .addLineToPoint: commands.append("L\(point(e.points[0]))")
            case .addQuadCurveToPoint: commands.append("Q\(point(e.points[0])) \(point(e.points[1]))")
            case .addCurveToPoint: commands.append("C\(point(e.points[0])) \(point(e.points[1])) \(point(e.points[2]))")
            case .closeSubpath: commands.append("Z")
            @unknown default: break
            }
        }
    }
}
let path = commands.joined()
let wordmarkEm = number(advanceEm("clear", roman) + advanceEm("af", italic))
let header = "Generated by scripts/brand/extract-glyphs.swift from \(italicFont). Do not edit."

let swiftFile = """
// \(header)
import CoreGraphics

enum LetterpressMarkGlyphs {
    /// The "af" monogram in em units, y down, origin at the bottom-right of its line box (line-height 1).
    static let path = "\(path)"
    /// Advance of "clear" (Newsreader Light) + "af" (Light Italic) in em, before tracking.
    static let wordmarkAdvanceEm: CGFloat = \(wordmarkEm)
}

"""
let tsFile = """
// \(header)

/** The "af" monogram in em units, y down, origin at the bottom-right of its line box (line-height 1). */
export const MARK_GLYPH_PATH = "\(path)";
/** Advance of "clear" (Newsreader Light) + "af" (Light Italic) in em, before tracking. */
export const WORDMARK_ADVANCE_EM = \(wordmarkEm);

"""

let check = CommandLine.arguments.contains("--check")
var stale: [String] = []
for (file, text) in [(swiftOutput, swiftFile), (tsOutput, tsFile)] {
    if check {
        if (try? String(contentsOfFile: file, encoding: .utf8)) != text { stale.append(file) }
    } else {
        try! FileManager.default.createDirectory(atPath: (file as NSString).deletingLastPathComponent, withIntermediateDirectories: true)
        try! text.write(toFile: file, atomically: true, encoding: .utf8)
        print("wrote \(file)")
    }
}
if check {
    if stale.isEmpty { print("mark glyphs are current") } else { print("stale: \(stale.joined(separator: ", "))"); exit(1) }
}
