import {test,before,beforeEach,after} from 'node:test';
import assert from 'node:assert/strict';
import {randomUUID} from 'node:crypto';
import Module from 'node:module';
import express from 'express';
const A=randomUUID(),B=randomUUID(),C=randomUUID(),D=randomUUID();
let rows:any[]=[],photos:any[]=[],routines:any[]=[],assigned=C,afterLock:(()=>void)|undefined,queue=Promise.resolve();
function matches(row:any,where:any={}):boolean{return Object.entries(where).every(([key,value]:any)=>{if(key==='OR')return value.some((v:any)=>matches(row,v));if(value&&typeof value==='object'&&!(value instanceof Date)){if('in' in value)return value.in.includes(row[key]);if('lt' in value)return row[key]<value.lt;}return value instanceof Date?row[key]?.getTime()===value.getTime():row[key]===value})}
function model(get:()=>any[]){return {findUnique:async({where}:any)=>get().find(r=>matches(r,where))??null,findFirst:async(args:any)=> (await model(get).findMany(args))[0]??null,findMany:async({where,orderBy,take}:any={})=>{const found=get().filter(r=>matches(r,where));if(orderBy)found.sort((a,b)=>{for(const order of Array.isArray(orderBy)?orderBy:[orderBy]){const [k,d]=Object.entries(order)[0];if(a[k]<b[k])return d==='desc'?1:-1;if(a[k]>b[k])return d==='desc'?-1:1}return 0});return found.slice(0,take)},count:async({where}:any)=>get().filter(r=>matches(r,where)).length,create:async({data}:any)=>{if(get().some(r=>r.id===data.id))throw Object.assign(Error(),{code:'P2002'});const row={...data,sentAt:new Date('2026-09-13T00:00:00.000Z'),readAt:null,origin:'native'};get().push(row);return row},updateMany:async({where,data}:any)=>{const found=get().filter(r=>matches(r,where));found.forEach(r=>Object.assign(r,data));return {count:found.length}}}}
const db:any={assignedMessage:model(()=>rows),skinPhoto:model(()=>photos),careRoutineRevision:model(()=>routines),user:model(()=>[{id:A,name:'A',dermatologistId:assigned},{id:B,name:'B',dermatologistId:D}]),dermatologist:model(()=>[{id:C,name:'C'},{id:D,name:'D'}]),$queryRaw:async()=>{afterLock?.();afterLock=undefined;return [{id:A}]},$transaction:async(fn:any)=>{const prior=queue;let release!:()=>void;queue=new Promise(r=>release=r);await prior;try{return await fn(db)}finally{release()}}};
const original=(Module as any)._load;(Module as any)._load=function(name:string,...args:any[]){if(name==='@prisma/client')return {PrismaClient:class{constructor(){return db}}};return original.call(this,name,...args)};
const app=express();app.use(express.json());app.use((req:any,res,next)=>{const id=req.header('x-identity');if(!id)return res.sendStatus(401);req.user={id,userType:[C,D].includes(id)?'dermatologist':'patient',email:'synthetic@test.invalid'};next()});app.use('/messages',require('../src/routes/assigned-messages').default);app.use(require('../src/middleware/errorHandler').errorHandler);(Module as any)._load=original;
let server:any,base:string;before(async()=>{server=app.listen(0,'127.0.0.1');await new Promise<void>(r=>server.once('listening',r));base=`http://127.0.0.1:${server.address().port}/messages`});after(()=>new Promise<void>(r=>server.close(r)));beforeEach(()=>{rows=[];photos=[];routines=[];assigned=C;afterLock=undefined});
const pair=`/patients/${A}/clinicians/${C}`;
async function call(path:string,who=A,method='GET',body?:any){const r=await fetch(base+path,{method,headers:{'x-identity':who,'content-type':'application/json'},body:body===undefined?undefined:JSON.stringify(body)});return {status:r.status,body:await r.json().catch(()=>({})) as any}}
const send=(id=randomUUID(),who=A,content='Synthetic text',reference:any=null)=>call(pair+'/messages/'+id,who,'PUT',{content,reference});
test('pair access and endpoint roles denied; assignment rechecked after lock before replay',async()=>{assert.equal((await call('/inbox',A)).status,403);assert.equal((await call('/current',C)).status,403);assert.equal((await call(pair,D)).status,404);assert.equal((await call(pair,B)).status,404);const id=randomUUID();assert.equal((await send(id)).status,201);afterLock=()=>{assigned=D};assert.equal((await send(id)).status,404);assert.equal((await call(pair)).status,404);assert.equal(rows.length,1)});
test('concurrent retries retain one exact message; sender/body/global ID conflict concealed',async()=>{const id=randomUUID();assert.deepEqual((await Promise.all([send(id),send(id)])).map(r=>r.status).sort(),[200,201]);assert.equal(rows.length,1);assert.equal((await send(id,A,'Changed')).status,409);assert.equal((await send(id,C)).status,409);const result=await call(`/patients/${B}/clinicians/${D}/messages/${id}`,B,'PUT',{content:'Synthetic text',reference:null});assert.equal(result.status,409);assert.equal(result.body.message,undefined)});
test('equal timestamps paginate without skips; pair-bound cursors; fetch never marks read',async()=>{for(let i=0;i<5;i++)await send();const first=await call(pair+'?limit=2',C),second=await call(pair+'?limit=2&before='+first.body.nextCursor,C),third=await call(pair+'?limit=2&before='+second.body.nextCursor,C);assert.equal(first.body.conversation.unreadCount,5);assert.equal(third.body.nextCursor,null);const ids=[...first.body.messages,...second.body.messages,...third.body.messages].map(r=>r.id);assert.equal(new Set(ids).size,5);assert.deepEqual(ids,[...ids].sort().reverse());assert(rows.every(r=>r.readAt===null));assert.equal((await call(`/patients/${B}/clinicians/${D}?before=${first.body.nextCursor}`,D)).status,400)});
test('read acknowledgement all-or-none exact recipient IDs and idempotent',async()=>{const a=randomUUID(),b=randomUUID(),reply=randomUUID();await send(a);await send(b);await send(reply,C);assert.equal((await call(pair+'/read',C,'POST',{messageIds:[a,reply]})).status,404);assert(rows.every(r=>r.readAt===null));assert.equal((await call(pair+'/read',A,'POST',{messageIds:[a]})).status,404);const result=await call(pair+'/read',C,'POST',{messageIds:[a]});assert.equal(result.body.unreadCount,1);assert.deepEqual(result.body.acknowledgedIds,[a]);assert.equal((await call(pair+'/read',C,'POST',{messageIds:[a]})).body.unreadCount,1);assigned=D;assert.equal((await call(pair+'/read',C,'POST',{messageIds:[b]})).status,404);assert.equal(rows.find(r=>r.id===b).readAt,null)});
test('references are clinician-only exact patient owned, unavailable after deletion, and reauthorized',async()=>{const photo=randomUUID(),routine=randomUUID();photos.push({id:photo,userId:A,captureDate:new Date(),createdAt:new Date(),photoUrl:'private'});routines.push({id:routine,userId:B,name:'Other',createdAt:new Date()});assert.equal((await send(randomUUID(),A,'Text',{type:'photo',id:photo})).status,403);assert.equal((await send(randomUUID(),C,'Text',{type:'routineRevision',id:routine})).status,404);const id=randomUUID(),result=await send(id,C,'Text',{type:'photo',id:photo});assert.equal(result.status,201);assert.equal(result.body.message.reference.available,true);assert.equal(result.body.message.photoUrl,undefined);photos=[];const detail=await call(pair+'/messages/'+id+'/reference');assert.equal(detail.body.reference.available,false);assert.equal(detail.body.reference.label,null);assigned=D;assert.equal((await call(pair+'/messages/'+id+'/reference')).status,404)});
