import {Prisma,AssignedMessage} from '@prisma/client';
import {z} from 'zod';
import {prisma} from '../config/database';
import {messageInput,decodeCursor,encodeCursor,messageCursor,inboxCursor,MESSAGE_LIMIT_WINDOW_MS} from './assignedMessagesValidation';
type DB=Prisma.TransactionClient;
export type Identity={id:string,userType:string};
export type Pair={patientId:string,clinicianId:string};
export type MessageLimit={canSend:boolean,nextAllowedAt:string|null,reason:'reply-window'|'weekly'};
export const messageError=(statusCode:number,code:string)=>Object.assign(new Error(statusCode===500?'Message operation failed':code),{statusCode,code});
const unavailable=()=>messageError(404,'CONVERSATION_UNAVAILABLE');
function member(me:Identity,pair:Pair){if(!['patient','dermatologist'].includes(me.userType))throw messageError(403,'INSUFFICIENT_PERMISSIONS');if(me.id!==(me.userType==='patient'?pair.patientId:pair.clinicianId))throw unavailable()}
async function lock(db:DB,id:string,write=false){if(write)await db.$queryRaw`SELECT id FROM public.user_profiles WHERE id=${id}::uuid FOR UPDATE`;else await db.$queryRaw`SELECT id FROM public.user_profiles WHERE id=${id}::uuid FOR SHARE`}
async function authorize(db:DB,me:Identity,pair:Pair){member(me,pair);const patient=await db.user.findUnique({where:{id:pair.patientId},select:{name:true,dermatologistId:true}});if(!patient||patient.dermatologistId!==pair.clinicianId)throw unavailable();const clinician=await db.dermatologist.findUnique({where:{id:pair.clinicianId},select:{name:true}});if(!clinician)throw unavailable();return {patient,clinician}}
const received=(me:Identity)=>({recipientId:me.id,recipientType:me.userType});
async function reference(db:DB,patientId:string,type:string|null,id:string|null,detail=false){
 if(!type||!id)return null;
 if(type==='photo'){const photo=await db.skinPhoto.findFirst({where:{id,userId:patientId},select:{id:true,captureDate:true,createdAt:true}});return {type,id,available:!!photo,label:photo?'Photo':null,occurredAt:photo?.captureDate.toISOString()??null,...(detail&&photo?{photo}: {})}}
 const routine=await db.careRoutineRevision.findFirst({where:{id,userId:patientId},select:{id:true,userId:true,timeOfDay:true,version:true,name:true,isActive:true,steps:true,createdAt:true}});
 return {type,id,available:!!routine,label:routine?.name??null,occurredAt:routine?.createdAt.toISOString()??null,...(detail&&routine?{routine}: {})};
}
async function dto(db:DB,me:Identity,row:AssignedMessage){return {id:row.id,patientId:row.patientId,clinicianId:row.clinicianId,senderId:row.senderId,senderType:row.senderType,recipientId:row.recipientId,recipientType:row.recipientType,content:row.content,sentAt:row.sentAt.toISOString(),unreadForMe:row.recipientId===me.id&&row.recipientType===me.userType&&!row.readAt,reference:await reference(db,row.patientId,row.referenceType,row.referenceId),origin:'native' as const}}
const order=[{sentAt:'desc' as const},{id:'desc' as const}];
// A patient may start one new thread every rolling MESSAGE_LIMIT_WINDOW_MS, but may always reply within
// that window of the clinician's last message to them. Clinician messages are never limited; this is
// evaluated only for patient sends. Reads the same snapshot the send() transaction is already inside.
async function patientLimit(db:DB,pair:Pair,now:Date):Promise<MessageLimit>{
 const windowStart=new Date(now.getTime()-MESSAGE_LIMIT_WINDOW_MS);
 const clinicianReply=await db.assignedMessage.findFirst({where:{...pair,senderType:'dermatologist',sentAt:{gte:windowStart}},orderBy:order});
 if(clinicianReply)return {canSend:true,nextAllowedAt:null,reason:'reply-window'};
 const lastPatientMessage=await db.assignedMessage.findFirst({where:{...pair,senderType:'patient'},orderBy:order});
 if(lastPatientMessage&&lastPatientMessage.sentAt.getTime()>=windowStart.getTime())return {canSend:false,nextAllowedAt:new Date(lastPatientMessage.sentAt.getTime()+MESSAGE_LIMIT_WINDOW_MS).toISOString(),reason:'weekly'};
 return {canSend:true,nextAllowedAt:null,reason:'weekly'};
}
async function summary(db:DB,me:Identity,pair:Pair,names:Awaited<ReturnType<typeof authorize>>){const last=await db.assignedMessage.findFirst({where:pair,orderBy:order});return {...pair,patientName:names.patient.name,clinicianName:names.clinician.name,lastMessage:last?await dto(db,me,last):null,unreadCount:await db.assignedMessage.count({where:{...pair,...received(me),readAt:null}})}}
export async function current(me:Identity,now:Date=new Date()){return prisma.$transaction(async db=>{await lock(db,me.id);const patient=await db.user.findUnique({where:{id:me.id},select:{dermatologistId:true}});if(!patient?.dermatologistId)return {conversation:null};const pair={patientId:me.id,clinicianId:patient.dermatologistId};const conversation=await summary(db,me,pair,await authorize(db,me,pair));return {conversation:{...conversation,limit:await patientLimit(db,pair,now)}}})}
export async function inbox(me:Identity,limit:number,raw?:string){const cursor=raw?decodeCursor(raw,inboxCursor):null;if(cursor&&cursor.clinicianId!==me.id)throw messageError(400,'INVALID_CURSOR');return prisma.$transaction(async db=>{
 const candidates=cursor?await db.$queryRaw<{id:string}[]>`SELECT id FROM public.user_profiles WHERE "dermatologistId"=${me.id}::uuid AND id>${cursor.patientId}::uuid ORDER BY id ASC LIMIT ${limit+1} FOR SHARE`:await db.$queryRaw<{id:string}[]>`SELECT id FROM public.user_profiles WHERE "dermatologistId"=${me.id}::uuid ORDER BY id ASC LIMIT ${limit+1} FOR SHARE`;
 const rows=candidates.slice(0,limit);const conversations=[];for(const row of rows){const pair={patientId:row.id,clinicianId:me.id};conversations.push(await summary(db,me,pair,await authorize(db,me,pair)))}return {conversations,nextCursor:candidates.length>limit?encodeCursor({v:1,clinicianId:me.id,patientId:rows[rows.length-1].id}):null};
})}
export async function page(me:Identity,pair:Pair,limit:number,raw?:string){const cursor=raw?decodeCursor(raw,messageCursor):null;if(cursor&&(cursor.patientId!==pair.patientId||cursor.clinicianId!==pair.clinicianId))throw messageError(400,'INVALID_CURSOR');return prisma.$transaction(async db=>{await lock(db,pair.patientId);const names=await authorize(db,me,pair);const rows=await db.assignedMessage.findMany({where:{...pair,...(cursor?{OR:[{sentAt:{lt:new Date(cursor.sentAt)}},{sentAt:new Date(cursor.sentAt),id:{lt:cursor.id}}]}:{})},orderBy:order,take:limit+1});const shown=rows.slice(0,limit),last=shown[shown.length-1];return {conversation:await summary(db,me,pair,names),messages:await Promise.all(shown.map(row=>dto(db,me,row))),nextCursor:rows.length>limit?encodeCursor({v:1,...pair,sentAt:last.sentAt.toISOString(),id:last.id}):null}})}
export async function send(me:Identity,pair:Pair,id:string,input:z.infer<typeof messageInput>,now:Date=new Date()){const save=()=>prisma.$transaction(async db=>{await lock(db,pair.patientId,true);await authorize(db,me,pair);if(me.userType==='patient'&&input.reference)throw messageError(403,'INSUFFICIENT_PERMISSIONS');const existing=await db.assignedMessage.findUnique({where:{id}});if(existing){if(existing.patientId!==pair.patientId||existing.clinicianId!==pair.clinicianId||existing.senderId!==me.id||existing.senderType!==me.userType||existing.content!==input.content||existing.referenceType!==(input.reference?.type??null)||existing.referenceId!==(input.reference?.id??null))throw messageError(409,'MESSAGE_ID_CONFLICT');return {message:await dto(db,me,existing),created:false}}
 if(me.userType==='patient'){const limit=await patientLimit(db,pair,now);if(!limit.canSend)throw Object.assign(messageError(429,'PATIENT_MESSAGE_LIMIT'),{nextAllowedAt:limit.nextAllowedAt})}
 if(input.reference&&!(await reference(db,pair.patientId,input.reference.type,input.reference.id))?.available)throw messageError(404,'NOT_FOUND');
 const row=await db.assignedMessage.create({data:{id,...pair,senderId:me.id,senderType:me.userType,recipientId:me.userType==='patient'?pair.clinicianId:pair.patientId,recipientType:me.userType==='patient'?'dermatologist':'patient',content:input.content,referenceType:input.reference?.type??null,referenceId:input.reference?.id??null}});return {message:await dto(db,me,row),created:true};});try{return await save()}catch(error){if((error as {code?:string}).code!=='P2002')throw error;return save()}}
export async function acknowledge(me:Identity,pair:Pair,messageIds:string[]){return prisma.$transaction(async db=>{await lock(db,pair.patientId,true);await authorize(db,me,pair);const where={...pair,...received(me),id:{in:messageIds}};if(await db.assignedMessage.count({where})!==messageIds.length)throw messageError(404,'NOT_FOUND');await db.assignedMessage.updateMany({where:{...where,readAt:null},data:{readAt:new Date()}});return {acknowledgedIds:messageIds,unreadCount:await db.assignedMessage.count({where:{...pair,...received(me),readAt:null}})}})}
export async function openReference(me:Identity,pair:Pair,id:string){return prisma.$transaction(async db=>{await lock(db,pair.patientId);await authorize(db,me,pair);const row=await db.assignedMessage.findFirst({where:{...pair,id}});if(!row?.referenceId)throw messageError(404,'NOT_FOUND');const detail=await reference(db,pair.patientId,row.referenceType,row.referenceId,true);if(!detail)return {reference:null};const {routine,photo,...view}=detail as typeof detail & {routine?:unknown,photo?:unknown};return {reference:view,...(routine?{routine}:{}),...(photo?{photo}:{})}})}
