import { createClient } from '@supabase/supabase-js';
import dotenv from 'dotenv';
import { randomUUID } from 'node:crypto';

dotenv.config();

const supabaseUrl = process.env.SUPABASE_URL;
const supabaseAnonKey = process.env.SUPABASE_ANON_KEY;
const supabaseServiceKey = process.env.SUPABASE_SERVICE_ROLE_KEY;

if (!supabaseUrl || !supabaseAnonKey || !supabaseServiceKey) {
  throw new Error('Missing Supabase environment variables');
}

// Client for general operations (with anon key)
export const supabase = createClient(supabaseUrl, supabaseAnonKey);

// Admin client for file operations (with service role key)
export const supabaseAdmin = createClient(
  supabaseUrl,
  supabaseServiceKey,
  {
    auth: {
      autoRefreshToken: false,
      persistSession: false
    }
  }
);

// Storage bucket configuration
export const PHOTO_BUCKET = 'patient-photos';

// Object names are generated by the server, never taken from a client URL.
export function generatePhotoPath(userId: string, originalName: string): string {
  const extension = originalName.split('.').pop()?.toLowerCase();
  const safeExtension = ['jpg', 'jpeg', 'png', 'webp'].includes(extension || '') ? extension : 'jpg';
  return `${userId}/${randomUUID()}.${safeExtension}`;
}
